// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AmountUtils from "../../utils/AmountUtils.bs.js";

import './BalanceCmp.css'
;

function BalanceCmp(Props) {
  var transactions = Props.transactions;
  var netBalance = AmountUtils.calculateBalance(transactions);
  var sign = AmountUtils.check(netBalance);
  var color = netBalance >= 0.0 ? "positive-text" : "negative-text";
  var isRoundedBal = AmountUtils.isRounded(netBalance);
  var netBalance$1 = AmountUtils.round(netBalance, isRoundedBal);
  var netBalance$2 = AmountUtils.refactor(netBalance$1);
  return React.createElement("div", {
              className: "balance-container"
            }, React.createElement("p", {
                  className: "balance-title"
                }, "YOUR BALANCE"), React.createElement("p", {
                  className: "balance-amount " + color + ""
                }, "" + sign + " \u20B9" + netBalance$2 + ""));
}

var make = BalanceCmp;

export {
  make ,
}
/*  Not a pure module */
