// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "rescript/lib/es6/js_string.js";

function round(amount, isRoundedAmount) {
  if (isRoundedAmount) {
    return Js_string.concat("K", (amount / 10000000.0).toFixed(2));
  } else {
    return amount.toFixed(2);
  }
}

export {
  round ,
}
/* No side effect */
