// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

function calculateBalance(transactions) {
  return Belt_Array.reduce(transactions, 0.0, (function (acc, value) {
                var v = Belt_Float.fromString(value.amount);
                return acc + (
                        v !== undefined ? v : 0
                      );
              }));
}

function calculateIncome(transactions) {
  return Belt_Array.reduce(transactions, 0.0, (function (acc, value) {
                if (!Caml_obj.greaterequal(Belt_Float.fromString(value.amount), 0.0)) {
                  return acc + 0.0;
                }
                var v = Belt_Float.fromString(value.amount);
                return acc + (
                        v !== undefined ? v : 0
                      );
              }));
}

function calculateExpense(transactions) {
  return Belt_Array.reduce(transactions, 0.0, (function (acc, value) {
                if (!Caml_obj.lessthan(Belt_Float.fromString(value.amount), 0.0)) {
                  return acc + 0.0;
                }
                var v = Belt_Float.fromString(value.amount);
                return acc + (
                        v !== undefined ? v : 0
                      );
              }));
}

export {
  calculateBalance ,
  calculateIncome ,
  calculateExpense ,
}
/* No side effect */
