// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AmountRoundOf from "../../Utils/Functions/AmountRoundOf/AmountRoundOf.bs.js";
import * as IsRoundedAmount from "../../Utils/Functions/IsRoundedAmount/IsRoundedAmount.bs.js";
import * as CalculateAmounts from "../../Utils/Functions/CalculateAmounts/CalculateAmounts.bs.js";

import './IncomeExpense.css'
;

function IncomeExpense(Props) {
  var transactions = Props.transactions;
  var netIncome = CalculateAmounts.calculateIncome(transactions);
  var netExpense = CalculateAmounts.calculateExpense(transactions);
  var netExpense$1 = netExpense * -1.0;
  var isRoundedInc = IsRoundedAmount.isRounded(netIncome);
  var isRoundedExp = IsRoundedAmount.isRounded(netExpense$1);
  var netIncome$1 = AmountRoundOf.round(netIncome, isRoundedInc);
  var netExpense$2 = AmountRoundOf.round(netExpense$1, isRoundedExp);
  return React.createElement("div", {
              className: "income-expense-container"
            }, React.createElement("div", {
                  className: "income-container"
                }, React.createElement("p", {
                      className: "income-title"
                    }, "INCOME"), React.createElement("p", {
                      className: "income-amount"
                    }, "\u20B9" + netIncome$1 + "")), React.createElement("div", {
                  className: "vertical-line"
                }), React.createElement("div", {
                  className: "expense-container"
                }, React.createElement("p", {
                      className: "expense-title"
                    }, "EXPENSE"), React.createElement("p", {
                      className: "expense-amount"
                    }, "\u20B9" + netExpense$2 + "")));
}

var make = IncomeExpense;

export {
  make ,
}
/*  Not a pure module */
