// Generated by ReScript, PLEASE EDIT WITH CARE


function isRounded(amount) {
  if (amount <= -10000000.0) {
    return true;
  } else {
    return amount >= 10000000.0;
  }
}

export {
  isRounded ,
}
/* No side effect */
