// Generated by ReScript, PLEASE EDIT WITH CARE


function isRoundedBal(amount) {
  if (amount <= -10000000.0) {
    return true;
  } else {
    return amount >= 10000000.0;
  }
}

function isRoundedIncExp(amount) {
  return amount >= 10000000.0;
}

export {
  isRoundedBal ,
  isRoundedIncExp ,
}
/* No side effect */
