// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './Header.css'
;

function Header(Props) {
  return React.createElement("p", {
              className: "expense-tracker-header"
            }, "Expense Tracker");
}

var make = Header;

export {
  make ,
}
/*  Not a pure module */
