// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

function refactor(amount) {
  if (Caml_obj.lessthan(Belt_Float.fromString(amount), 0.0)) {
    return Js_string.sliceToEnd(1, amount);
  } else {
    return amount;
  }
}

export {
  refactor ,
}
/* No side effect */
