// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './History.css'
;

function $$History(Props) {
  return React.createElement("div", {
              className: "history-container"
            }, React.createElement("p", {
                  className: "history-title"
                }, "History"), React.createElement("hr", {
                  className: "horizontal-line"
                }));
}

var make = $$History;

export {
  make ,
}
/*  Not a pure module */
