// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";
import * as HistoryList from "./HistoryList.bs.js";

import './History.css'
;

function $$History(Props) {
  var transactions = Props.transactions;
  var notEmpty = function (x) {
    if (x.text !== "") {
      return x.amount !== "";
    } else {
      return false;
    }
  };
  var finalArray = transactions.filter(notEmpty);
  return React.createElement("div", {
              className: "history-container"
            }, React.createElement("p", {
                  className: "history-title"
                }, "History"), React.createElement("hr", {
                  className: "horizontal-line"
                }), React.createElement("div", {
                  className: "list"
                }, finalArray.map(function (ele) {
                      var sign = Caml_obj.greaterequal(Belt_Float.fromString(ele.amount), 0.0) ? "" : "-";
                      var stripColor = Caml_obj.greaterequal(Belt_Float.fromString(ele.amount), 0.0) ? "positive" : "negative";
                      var newAmount = Caml_obj.lessthan(Belt_Float.fromString(ele.amount), 0.0) ? Js_string.sliceToEnd(1, ele.amount) : ele.amount;
                      return React.createElement("div", {
                                  className: "list-items"
                                }, React.createElement(HistoryList.make, {
                                      text: ele.text,
                                      amount: newAmount,
                                      sign: sign,
                                      stripColor: stripColor
                                    }));
                    })));
}

var make = $$History;

export {
  make ,
}
/*  Not a pure module */
