// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './History.css'
;

function HistoryList(Props) {
  var text = Props.text;
  var amount = Props.amount;
  var sign = Props.sign;
  var stripColor = Props.stripColor;
  console.log(text);
  return React.createElement("div", {
              className: "list-items-content"
            }, React.createElement("p", {
                  className: "item-text"
                }, text), React.createElement("div", {
                  className: "amount-and-strip"
                }, React.createElement("p", {
                      className: "item-amount"
                    }, "" + sign + "\u20B9" + amount + ""), React.createElement("div", {
                      className: "strip " + stripColor + ""
                    })));
}

var make = HistoryList;

export {
  make ,
}
/*  Not a pure module */
