// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './Balance.css'
;

function Balance(Props) {
  return React.createElement("div", {
              className: "balance-container"
            }, React.createElement("p", {
                  className: "balance-title"
                }, "YOUR BALANCE"), React.createElement("p", {
                  className: "balance-amount"
                }, "0.00"));
}

var make = Balance;

export {
  make ,
}
/*  Not a pure module */
