// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

import './Balance.css'
;

function Balance(Props) {
  var transactions = Props.transactions;
  var netBalance = Belt_Array.reduce(transactions, 0.0, (function (acc, value) {
          var v = Belt_Float.fromString(value.amount);
          return acc + (
                  v !== undefined ? v : 0
                );
        }));
  var sign = netBalance >= 0.0 ? "" : "-";
  var color = netBalance >= 0.0 ? "positive-text" : "negative-text";
  var netBalance$1 = netBalance.toFixed(2);
  var netBalance$2 = Caml_obj.lessthan(Belt_Float.fromString(netBalance$1), 0.0) ? Js_string.sliceToEnd(1, netBalance$1) : netBalance$1;
  return React.createElement("div", {
              className: "balance-container"
            }, React.createElement("p", {
                  className: "balance-title"
                }, "YOUR BALANCE"), React.createElement("p", {
                  className: "balance-amount " + color + ""
                }, "" + sign + " \u20B9" + netBalance$2 + ""));
}

var make = Balance;

export {
  make ,
}
/*  Not a pure module */
