// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

import './Balance.css'
;

function Balance(Props) {
  var transactions = Props.transactions;
  var netBalance = Belt_Array.reduce(transactions, 0.0, (function (acc, value) {
          var v = Belt_Float.fromString(value.amount);
          return acc + (
                  v !== undefined ? v : 0
                );
        }));
  var netBalance$1 = String(netBalance);
  return React.createElement("div", {
              className: "balance-container"
            }, React.createElement("p", {
                  className: "balance-title"
                }, "YOUR BALANCE"), React.createElement("p", {
                  className: "balance-amount"
                }, "\u20B9" + netBalance$1 + ""));
}

var make = Balance;

export {
  make ,
}
/*  Not a pure module */
