// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './HeaderCmp.css'
;

function HeaderCmp(Props) {
  return React.createElement("p", {
              className: "expense-tracker-header"
            }, "Expense Tracker");
}

var make = HeaderCmp;

export {
  make ,
}
/*  Not a pure module */
