// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Header from "./components/Header/Header.bs.js";
import * as Balance from "./components/Balance/Balance.bs.js";
import * as $$History from "./components/History/History.bs.js";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as IncomeExpense from "./components/IncomeExpense/IncomeExpense.bs.js";
import * as AddTransactions from "./components/AddTransactions/AddTransactions.bs.js";

import './App.css'
;

var initialTransaction = [{
    text: "",
    amount: ""
  }];

function App(Props) {
  var match = React.useState(function () {
        return initialTransaction;
      });
  var setTransactions = match[1];
  var transactions = match[0];
  var addTransaction = function (text, amount) {
    var prevTransactionArray = transactions.slice();
    var latestTransaction = [{
        text: text,
        amount: amount
      }];
    var newTransactionArray = Js_array.concat(latestTransaction, prevTransactionArray);
    Curry._1(setTransactions, (function (param) {
            return newTransactionArray;
          }));
  };
  return React.createElement("div", {
              className: "main-container"
            }, React.createElement(Header.make, {}), React.createElement(Balance.make, {
                  transactions: transactions
                }), React.createElement(IncomeExpense.make, {
                  transactions: transactions
                }), React.createElement($$History.make, {
                  transactions: transactions
                }), React.createElement(AddTransactions.make, {
                  submitHandler: addTransaction
                }));
}

var make = App;

export {
  initialTransaction ,
  make ,
}
/*  Not a pure module */
