// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header from "./components/Header/Header.bs.js";
import * as Balance from "./components/Balance/Balance.bs.js";
import * as $$History from "./components/History/History.bs.js";
import * as IncomeExpense from "./components/IncomeExpense/IncomeExpense.bs.js";
import * as AddTransactions from "./components/AddTransactions/AddTransactions.bs.js";

import './App.css'
;

function App(Props) {
  return React.createElement("div", {
              className: "main-container"
            }, React.createElement(Header.make, {}), React.createElement(Balance.make, {}), React.createElement(IncomeExpense.make, {}), React.createElement($$History.make, {}), React.createElement(AddTransactions.make, {}));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
