name: Disable Merge on New Commits

# on:
#   pull_request:
#     types: [opened, synchronize]

on:
  workflow_dispatch

jobs:
  disable-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Get pull request details
        id: pr-details
        run: echo "::set-output name=branch::${{ github.event.pull_request.head.ref }}"

      - name: Disable merge by requiring a new check
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          BRANCH=${{ steps.pr-details.outputs.branch }}
          curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/$BRANCH/protection \
            -d '{
              "required_status_checks": {
                "strict": false,
                "contexts": ["fetch_pagespeed"]
              },
              "enforce_admins": false,
              "required_pull_request_reviews": null,
              "restrictions": null
            }'
