name : Testing - Pagespeed Insights
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy and test'
        required: true
        default: 'main'
      staging_url:
        description: 'The URL of the staging environment'
        required: true
        
jobs:
  fetch_pagespeed:
    runs-on: ubuntu-latest
    
    outputs:
      mobile-score: ${{ steps.pagespeed-mobile.outputs.mobile-score }}
      desktop-score: ${{ steps.pagespeed-desktop.outputs.desktop-score }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PageSpeed Insights API for Mobile
        id: pagespeed-mobile
        env:
          API_KEY: AIzaSyBMukdnJE28tcjeznqyH22-N_zSnW4JL7o
        run: |
          score=$(curl -s "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://porter.in&key=${API_KEY}&strategy=mobile" | jq '.lighthouseResult.categories.performance.score * 100')
          echo "::set-output name=mobile-score::$score"

      - name: Run PageSpeed Insights API for Desktop
        id: pagespeed-desktop
        env:
          API_KEY: AIzaSyBMukdnJE28tcjeznqyH22-N_zSnW4JL7o
        run: |
          score=$(curl -s "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://porter.in&key=${API_KEY}&strategy=desktop" | jq '.lighthouseResult.categories.performance.score * 100')
          echo "::set-output name=desktop-score::$score"

      - name: Check mobile performance score
        run: |
          mobileScore=${{ steps.pagespeed-mobile.outputs.mobile-score }}
          if (( $(echo "$mobileScore < 50" | bc -l) )); then
            echo "Mobile performance score is below the acceptable threshold (50)."
            exit 1
          fi

      - name: Check desktop performance score
        run: |
          desktopScore=${{ steps.pagespeed-desktop.outputs.desktop-score }}
          if (( $(echo "$desktopScore < 50" | bc -l) )); then
            echo "Desktop performance score is below the acceptable threshold (50)."
            exit 1
          fi

      - name: Set commit status to success
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_SHA=${{ github.sha }}
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"state": "success", "target_url": "", "description": "PageSpeed Check Passed", "context": "pagespeed-check"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA

      - name: Set commit status to failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_SHA=${{ github.sha }}
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"state": "failure", "target_url": "", "description": "PageSpeed Check Failed", "context": "pagespeed-check"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA
