name : Testing - Pagespeed Insights
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy and test'
        required: true
        default: 'main'
      staging_url:
        description: 'The URL of the staging environment'
        required: true
        
jobs:
  fetch_pagespeed:
    runs-on: ubuntu-latest
    
    outputs:
      mobile-score: ${{ steps.pagespeed-mobile.outputs.mobile-score }}
      desktop-score: ${{ steps.pagespeed-desktop.outputs.desktop-score }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Get commit SHA
        id: get-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Run PageSpeed Insights API for Mobile
        id: pagespeed-mobile
        env:
          API_KEY: AIzaSyBMukdnJE28tcjeznqyH22-N_zSnW4JL7o
        run: |
          score=$(curl -s "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${{ github.event.inputs.staging_url }}&key=${API_KEY}&strategy=mobile" | jq '.lighthouseResult.categories.performance.score * 100')
          echo "::set-output name=mobile-score::$score"

      - name: Run PageSpeed Insights API for Desktop
        id: pagespeed-desktop
        env:
          API_KEY: AIzaSyBMukdnJE28tcjeznqyH22-N_zSnW4JL7o
        run: |
          score=$(curl -s "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${{ github.event.inputs.staging_url }}&key=${API_KEY}&strategy=desktop" | jq '.lighthouseResult.categories.performance.score * 100')
          echo "::set-output name=desktop-score::$score"

      - name: Check mobile performance score
        run: |
          mobileScore=${{ steps.pagespeed-mobile.outputs.mobile-score }}
          if (( $(echo "$mobileScore < 50" | bc -l) )); then
            echo "Mobile performance score is below the acceptable threshold (50)."
            exit 1
          fi

      - name: Check desktop performance score
        run: |
          desktopScore=${{ steps.pagespeed-desktop.outputs.desktop-score }}
          if (( $(echo "$desktopScore < 50" | bc -l) )); then
            echo "Desktop performance score is below the acceptable threshold (50)."
            exit 1
          fi

      - name: Set commit status to success
        id: set-status
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          COMMIT_SHA=${{ steps.get-sha.outputs.sha }}
          RESPONSE=$(curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"state": "success", "target_url": "", "description": "PageSpeed Check Passed", "context": "fetch_pagespeed"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA)
          echo $RESPONSE
          echo "::set-output name=response::$(echo $RESPONSE | jq -r '.state')"

      - name: Get the pull request number
        id: get-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          PR_NUMBER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ steps.get-sha.outputs.sha }}/pulls" | jq -r '.[0].number')
          echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Enable branch merging if commit status is success
        if: steps.set-status.outputs.response == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          PR_NUMBER=${{ steps.get-pr.outputs.pr_number }}
          if [ "$PR_NUMBER" != "null" ]; then
            curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews \
              -d '{"event": "APPROVE"}'
            exit 0
          fi

      - name: Re-fetch pull request to check mergeability
        id: check-mergeable
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          PR_NUMBER=${{ steps.get-pr.outputs.pr_number }}
          if [ "$PR_NUMBER" != "null" ]; then
            PR_DETAILS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
            echo $PR_DETAILS
            MERGEABLE=$(echo $PR_DETAILS | jq -r '.mergeable')
            echo "::set-output name=mergeable::$MERGEABLE"
          fi

      - name: Set commit status to failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          COMMIT_SHA=${{ steps.get-sha.outputs.sha }}
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"state": "failure", "target_url": "", "description": "PageSpeed Check Failed", "context": "fetch_pagespeed"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA
          exit 1
