name: Remove Branch Protection on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  remove-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Get pull request details
        id: pr-details
        run: echo "::set-output name=branch::${{ github.event.pull_request.head.ref }}"

      - name: Remove branch protection rule
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          BRANCH=${{ steps.pr-details.outputs.branch }}
          curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/$BRANCH/protection
